"""add discount_type to offers

Revision ID: 5ab09e11bf2e
Revises: f02deece3554
Create Date: 2026-04-20 15:45:52.325925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ab09e11bf2e'
down_revision: Union[str, None] = 'f02deece3554'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offers', sa.Column('discount_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('offers', 'discount_type')
    # ### end Alembic commands ###
