"""add credits_used to orders table

Revision ID: 677aaa123e4a
Revises: f1e34a8a30a5
Create Date: 2026-04-10 01:40:31.543775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '677aaa123e4a'
down_revision: Union[str, None] = 'f1e34a8a30a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('credits_used', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'credits_used')
    # ### end Alembic commands ###
